"""changes tatto_image column name

Revision ID: 4a4ed8641c49
Revises: 6fa2f6c567c2
Create Date: 2022-03-07 12:46:12.876295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4ed8641c49'
down_revision = '6fa2f6c567c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tattoo_images', sa.Column('image_mimetype', sa.String(), nullable=False))
    op.drop_column('tattoo_images', 'iamge_mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tattoo_images', sa.Column('iamge_mimetype', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tattoo_images', 'image_mimetype')
    # ### end Alembic commands ###
