"""adds blocklist and removes unique password hash constraint

Revision ID: 718f09bea40b
Revises: 4a4ed8641c49
Create Date: 2022-03-08 22:34:07.890703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718f09bea40b'
down_revision = '4a4ed8641c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('clients_password_hash_key', 'clients', type_='unique')
    op.drop_constraint('tattooists_password_hash_key', 'tattooists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tattooists_password_hash_key', 'tattooists', ['password_hash'])
    op.create_unique_constraint('clients_password_hash_key', 'clients', ['password_hash'])
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
