"""changes materials atribute name

Revision ID: e625a84b325b
Revises: 718f09bea40b
Create Date: 2022-03-09 22:37:31.094817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e625a84b325b'
down_revision = '718f09bea40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('id_item', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('materials_id_storage_fkey', 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'storage', ['id_item'], ['id'])
    op.drop_column('materials', 'id_storage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('id_storage', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key('materials_id_storage_fkey', 'materials', 'storage', ['id_storage'], ['id'])
    op.drop_column('materials', 'id_item')
    # ### end Alembic commands ###
